Lesson 9 Tax Calculator
KacperKropidlowski/invoicing-system-kacper-kropidlowski pull request #11
Opened 2022-10-04 16:46 UTC by KacperKropidlowski

2022-10-05 08:19 UTC, patryk-stepniak requested changes
Kilka uwag

2022-10-05 08:19 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public BigDecimal income(String taxIdentificationNumber) {
Dlaczego public'i?

2022-10-05 08:19 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public TaxCalculatorResult calculateTaxes(String taxIdentificationNumber) {
Kolejnosc metod

2022-10-05 08:19 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorResult.java
> +  @ApiModelProperty (required = true, example = "20000")
brak opisu pola w adnotacji

2022-10-05 08:34 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorResult.java
> +  @ApiModelProperty (required = true, example = "20000")
Wydawało mi się że te nazwy są wystarczająco samoopisujące

2022-10-05 08:37 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public TaxCalculatorResult calculateTaxes(String taxIdentificationNumber) {
Poprawione

2022-10-05 08:38 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public BigDecimal income(String taxIdentificationNumber) {
Poprawione

2022-10-05 08:38 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorResult.java
> +  @ApiModelProperty (required = true, example = "20000")
Ale poprawiłem i tak

2022-10-06 08:51 UTC, patryk-stepniak approved these changes

2022-10-06 08:51 UTC, merged